name: data
channels:
  - defaults
dependencies:
  - pip=23.0.1
  - python=3.9.16
  - pip:
      - numpy==1.24.2
      - pandas==1.3.2
      - psycopg2==2.9.5
      - openpyxl==3.1.2
      - pypdf2==3.0.1
      - tqdm==4.65.0
      - ipykernel==6.22.0
      - knoema==1.2.46
      - google-api-python-client==2.81.0
      - google-auth-httplib2==0.1.0
      - google-auth-oauthlib==1.0.0