name: Data Loader CI/CD

on:
  push:
    branches: [ data_ingestion ]
  pull_request:
    branches: [ data_ingestion ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.16

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt